[package]
name = "calcium"
version = "0.1.0"
edition = "2021"

[lib]
name = "calcium_lib"
path = "src/lib/lib.rs"

[[bin]]
name = "calcium"
path = "src/bin/bin.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.2.1"
chrono = { version = "0.4.23", features = ["std", "serde"] }
num-traits = "0.2.15"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
thiserror = "1.0.38"
uuid = { version = "1.2.2", features = ["v4", "fast-rng", "serde"] }
